# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1

# =================================
# = Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realmeet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.gmail.com
    username: writeyourshippingemail@gmail.com
    password: writeyourpassword
    from: writethetargetemail@gmail.com
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 587
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: INFO
    org.flywaydb: INFO

# =================================
# = RealMeet
# =================================
realmeet:
  allocation:
    maxFilterLimit: 50
  email:
    templates:
      allocationCreated:
        subject: Novo agendamento de sala criado!
        templateName: allocation-created.html
      allocationUpdated:
        subject: Agendamento de sala alterado!
        templateName: allocation-updated.html
      allocationDeleted:
        subject: Agendamento de sala exclu√≠do!
        templateName: allocation-deleted.html
